### ISSUE TITLE
Keeping iframes open/active in bg when minimized

### ISSUE THREAD

**Issue by DustinBrett** [DustinBrett/daedalOS#119]
### Discussed in https://github.com/DustinBrett/daedalOS/discussions/118

<div type='discussions-op-text'>

<sup>Originally posted by **markus-li** March 11, 2022</sup>
Not truly dug into the code yet, but wanted to ask, is there an easy way to keep iframes open/active while minimized to the taskbar? As it is now they're closed and then reloaded when unminimized.</div>

Thanks for this comment @markus-li

**Comment by markus-li** [comment]
There are times when doing it as it is now would be beneficial, for example a heavy-on-resources page which will restore state anyway. Making this optional once made possible to not have the iframe destroyed could be beneficial in my opinion.

**Comment by markus-li** [comment]
This is probably not an issue, dug into your code and the issue only existed in my own app due to setting the location of the iframe again upon load. Your browser app does this flawlessly. Sorry to have caused you concern.

**Comment by DustinBrett** [comment]
Ah ok, well glad to hear that at least. Thanks for checking it out!
