### ISSUE TITLE
Bring the Windows Start button back

### ISSUE THREAD

**Issue by Pixel556** [DustinBrett/daedalOS#121]
Hello! I noticed that the start button was changed to a pi symbol. Please change it back so it looks more realistic.
![image](https://user-images.githubusercontent.com/95143545/158073941-25b3dc49-7e0d-4a13-b0bb-8a6a6676cdf7.png)

**Comment by DustinBrett** [comment]
Thanks for the suggestion but some friendly legal folks asked me nicely to change it and I happily obliged. :-)
