### ISSUE TITLE
Opening terminal on IOS Safari bug

### ISSUE THREAD

**Issue by u9g** [DustinBrett/daedalOS#125]
Opening terminal in safari causes the website to redirect back to the homepage

**Comment by DustinBrett** [comment]
Thanks for this report! I added WebGL recently with a fallback, but maybe it's broken or never worked. I'll look into it.

**Comment by DustinBrett** [comment]
Thanks to the awesomeness of BrowserStack (https://www.browserstack.com/open-source) I've managed to get myself a license to test on Safari. I'll be getting to the bottom of this issue ASAP. Along with a bunch of other browser compat issues I am likely to find.

**Comment by DustinBrett** [comment]
Fixed this. Safari seems to have some WebGL support, but not enough for [xterm](https://www.npmjs.com/package/xterm-addon-webgl).
