### ISSUE TITLE
esheep alias not working

### ISSUE THREAD

**Issue by kumavis** [DustinBrett/daedalOS#127]
https://github.com/DustinBrett/daedalOS/blob/465e163da61226009b4ba2153a3cf6916342fdba/components/apps/Terminal/functions.ts#L77

![image](https://user-images.githubusercontent.com/1474978/160943909-fe274045-39b2-4ce8-8591-4a7406a2fe8b.png)

**Comment by DustinBrett** [comment]
Fixed in latest commit.
