### ISSUE TITLE
example "wapm fortune" outputs nothing

### ISSUE THREAD

**Issue by kumavis** [DustinBrett/daedalOS#134]
both `wapm fortune` and `wax fortune` output nothing. (cowsay works fine with both)

**Comment by kumavis** [comment]
![image](https://user-images.githubusercontent.com/1474978/161915117-c031d5b2-7df7-45c2-bc61-db141997f9d5.png)

**Comment by DustinBrett** [comment]
Ah thanks! That is the risk I guess with `wapm` as it pulls these files directly from their repository. I see it's 404 now. I will try and add an error in Terminal to make that clear.

![image](https://user-images.githubusercontent.com/16656318/162109495-736deedd-444f-4c0a-a9f4-89ce2db5b94b.png)
****

**Comment by DustinBrett** [comment]
Now 404's show as command not found.
