### ISSUE TITLE
Microsoft Edge says website is malicious

### ISSUE THREAD

**Issue by hello-smile6** [DustinBrett/daedalOS#148]
![image](https://user-images.githubusercontent.com/73048226/168184735-34dfeda1-39c2-4672-9f61-350a17bf72fc.png)
I know it's not, but still.
Dispute link: https://feedback.smartscreen.microsoft.com/feedback.aspx

**Comment by DustinBrett** [comment]
Thanks for mentioning this. I just submitted a dispute because I have no idea why it's saying this. I do use a lot of libs as this repo shows, but none are malicious afaik and if they are I'd love to know.

**Comment by DustinBrett** [comment]
At least on mobile Edge with Smart screen it seems ok. I'll keep an eye on it and try in other browsers via BrowserStack. Thanks again.

**Comment by hello-smile6** [comment]
> At least on mobile Edge with Smart screen it seems ok. I'll keep an eye on it and try in other browsers via BrowserStack. Thanks again.

I'll see if I can reproduce with VNC. The v86 custom profile URL also was flagged in the past, https://github.com/copy/v86/issues/567

**Comment by DustinBrett** [comment]
They've replied that it will be reviewed within 48 business hours. Hopefully it will be resolved without issue as I have nothing malicious on the site of any kind and the source is wide open.

**Comment by hello-smile6** [comment]
> They've replied that it will be reviewed within 48 business hours. Hopefully it will be resolved without issue as I have nothing malicious on the site of any kind and the source is wide open.

Could it be something about v86, maybe?

**Comment by DustinBrett** [comment]
Could be all sorts of things tbh as I use 20+ libs from other OSS projects. I will see what they say. As far as cookies or personal data or any stray network requests, I don't see any of that and I have always kept an eye for that and used reputable packages as much as I could. I don't see this being flagged anywhere else at least. Maybe someone reported it to be a jerk.

**Comment by DustinBrett** [comment]
I've added CSP and HSTS and done a bunch of scans of various things. Not sure what the original issue/report could be. Still blocked so we will see how it goes early next week.

**Comment by DustinBrett** [comment]
Got rid of CSP as it's annoying to get right and with apps I have like Browser and Video Player, it needs to be open. Still blocked on Edge, although it seems delayed sometimes which is odd. Also Edge mobile works yet claims to use SmartScreen. My best guess is someone reporting my site thinking it wasn't just client side or some kind of false positive. But I know I have nothing malicious so I hope this dispute system resolves it.

**Comment by DustinBrett** [comment]
I don't wanna jinx it but it seems resolved. I haven't heard back from them but atm it worked for me. Perhaps others could test when they have time.

**Comment by hello-smile6** [comment]
> I don't wanna jinx it but it seems resolved. I haven't heard back from them but atm it worked for me. Perhaps others could test when they have time.

Seems to be resolved for me

**Comment by DustinBrett** [comment]
Great! Thanks for reporting/testing. Glad it's resolved. MS was indeed 2 business days, so I'll give them credit on reporting working. Closing issue.
