### ISSUE TITLE
Background blur w/Terminal in Firefox

### ISSUE THREAD

**Issue by Cveinnt** [DustinBrett/daedalOS#150]
Hello, I noticed this line 
https://github.com/DustinBrett/daedalOS/blob/243f57bfaa31b37a05ac75b455277a2887f87d04/components/apps/Terminal/StyledTerminal.ts#L10
when trying to style the terminal. However, it doesn't seem to be working as `backdrop-filter` is considered an invalid property name in developer tools. 

I looked up xterm's documentations and couldn't seem to find anything related. 

Is there a proper way to create a blurred terminal background? Or is it not currently supported?

**Comment by DustinBrett** [comment]
Hi @Cveinnt,

That property is supported in all browsers except Firefox.
https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter#browser_compatibility

Sadly there is not an easy way to get the exact same blur effect in Firefox. Or if there is I haven't found the perfect one yet. I have seen some people try using the svg blur but it gave me issues around the edges.

**Comment by DustinBrett** [comment]
Do you happen to be using Firefox or another browser not on that list? If so maybe I can keep this issue but rename to specify that it's browser specific.

**Comment by Cveinnt** [comment]
Hi Dustin, thanks for the reply! 

Oddly this issue is present for me on other browsers as well - tested this on chrome/brave/safari on macOS, as well as chrome/brave/edge on Windows. The background blur effect is only working on Safari. 

Interestingly, `backdrop-filter` is working for the task bar on all other browsers except Firefox, but not for the terminal.

**Comment by DustinBrett** [comment]
I'm not having this issue in this codebase. I'll test a bit more but otherwise this can be closed as this prop works as expected in my tests.

**Comment by Cveinnt** [comment]
This is is present for me on [dustinbrett.com](dustinbrett.com) as well, assuming it uses the latest codebase. As shown,

![scrnsht](https://user-images.githubusercontent.com/30604389/169315533-688b41b6-7683-4511-8a7e-151fe8ad5c7b.png)

background blur for terminal is only working on Safari, not Chrome

**Comment by DustinBrett** [comment]
I'm not sure why it's not working in Chrome for you. I'll test it more as that CSS prop should work and was for me.

**Comment by DustinBrett** [comment]
For me on Chrome it's not doing this. But something is odd because it showed on Edge wrong now even though that is Chromium based. I will look into this. It works sometimes so something is going on, it won't ever work in FF but every other browser should work.

Whatever blur I can manage out of the terminal, it's likely gonna happen via this CSS prop, so just need to figure out why it's not working. This prop is unique in that it can't be stacked, so sometimes the stacking context can confuse it as to which backdrop it's blurring.

![image](https://user-images.githubusercontent.com/16656318/169329563-ea1ec54c-58c2-4abb-91a1-1923e76507b4.png)

**Comment by DustinBrett** [comment]
Looks to have been related to the addition of `will-change` as an attempt at a performance optimization. I've decided to remove it for now till I understand it's full usage better on every browser.

With this removed it blurs properly on Edge for me now.

https://github.com/DustinBrett/daedalOS/commit/73fd68c928c0723021017a5e8a4e6728296e7a6c

**Comment by Cveinnt** [comment]
Thank you for investigating - removing `will-change` did the trick for me as well! 
Should I close this issue or leave it open in case Firefox supports `backdrop-filter` in the future?

**Comment by DustinBrett** [comment]
I will close it cause FF blur support is something I have spent way too much time on already. If someone else ever figures it out, would be cool. I see a lot of people on CodePen trying but I've never had it look exactly the same with no blur bleed or edge issues using the SVG filter tricks.

Thanks for reporting this, I don't know why my Chrome worked and Edge didn't, but I also don't know enough about `will-change` and shouldn't have messed with it yet maybe.

**Comment by DustinBrett** [comment]
I think `will-change` was making a new stacking context which doesn't work right with `backdrop-filter`, as it also creates a stacking context.

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

![image](https://user-images.githubusercontent.com/16656318/169388587-26a74a7f-25b6-4f01-bf22-57c11fa32ba0.png)

**Comment by DustinBrett** [comment]
Possibly I should only apply `will-change` during adjustments to the window, but also I don't think it made any real performance difference in my testing.

https://dev.opera.com/articles/css-will-change-property/

**Comment by DustinBrett** [comment]
Firefox is going to get blur support in 103. I tried it and it worked. Waiting was the answer!

**Comment by DustinBrett** [comment]
Indeed today it came true. Firefox v103 has backdrop-filter by default and my blurs are working. This wasn't even mentioned in their release notes!!!
