### ISSUE TITLE
Terminal text disappears upon wallpaper change

### ISSUE THREAD

**Issue by Cveinnt** [DustinBrett/daedalOS#151]
As titled - terminal text would mysteriously disappear upon wallpaper change, only leaving the cursor blinking in the same place.

### Steps to reproduce:
1. Open a terminal
2. Change wallpaper with right click menu

**Comment by DustinBrett** [comment]
Thanks, I have noticed this once or twice but didn't connect it to the wallpaper. I will look into this. I think switching to WebGL might help for browsers that support it but also it has some issues.

**Comment by DustinBrett** [comment]
Resolved, I had sloppy code deleting canvas's

https://github.com/DustinBrett/daedalOS/commit/76474ab2c9590a4dc572499a4c36745c48a93ce5
