### ISSUE TITLE
BoxedWine can't run Windows XP Pinball

### ISSUE THREAD

**Issue by hello-smile6** [DustinBrett/daedalOS#169]
I have a copy of the Windows XP Pinball game. It runs perfectly with both Wine and Windows 10, but doesn't work because the entire directory it is in isn't mounted.

**Comment by DustinBrett** [comment]
Anything BoxedWine can't do should be posted to BoxedWine GitHub. That being said they have the demo on their page which works.

http://www.boxedwine.org/app/full-tilt-pinball/

Also this demo works on my app.

![image](https://user-images.githubusercontent.com/16656318/172088641-ad26ffdc-600d-4ae6-8f40-5f8361098b85.png)

To run an app in BoxedWine, ideally it should be zipped with any files it requires to run. If just .exe is clicked it will only run that within BoxedWine and not it's supporting docs.

I ran `title95.zip` directly in BoxedWine.

![image](https://user-images.githubusercontent.com/16656318/172088753-c8c80597-71ca-4090-b793-b623dc34b906.png)

**Comment by hello-smile6** [comment]
Okay, I'll try using my .zip file. (I actually have a .zip with it mounted on my actual computer, that's the directory it's mounted from)

**Comment by hello-smile6** [comment]
For some reason, my directory has a .zip extension, and I got a file right-click menu.

**Comment by DustinBrett** [comment]
If you have a specific issue please post screenshots/descriptions and details that can be actioned on.

**Comment by hello-smile6** [comment]
Okay.

**Comment by hello-smile6** [comment]
It works now, sorry.

**Comment by DustinBrett** [comment]
Np, feel free to report.
