### ISSUE TITLE
Vim not showing content of some existing files

### ISSUE THREAD

**Issue by vi** [DustinBrett/daedalOS#172]
"Open With -> Vim" open Vim for creating a new file, not showing content of existing one.

**Comment by DustinBrett** [comment]
To clarify are you saying being able to open 2 Vim instances at the same time? If so unfortunately that is not supported at the moment.

**Comment by vi** [comment]
Single Vim instance, but maybe the file path is wrong, so it does not show content and shows `[new]` at the bottom.

**Comment by DustinBrett** [comment]
So if the file is empty and you do Open With it shows `[new]` at the bottom of Vim? That is the issue? Or where do you click Open With on?

**Comment by vi** [comment]
Steps to reproduce:

1. Go to https://dustinbrett.com/ in Firefox 91.10.0esr.
2. Double-click "My PC"
3. Right-click "robots.txt". Dismiss Firefox's native menu. Observe "Open" menu item and "Open with" subment.
4. Go to "Open width" and select "Vim" menu item.
5. Vim opens.

Expected:

Vim shows content like "User-agent: ...; Allow: ...", just like Monaco editor that gets opened by default.

Actual:

Vim's title is `robots.txt - Vim`, Vim's stats shows `"~/robots.txt" [New File]`, no content inside.

Issuing `:e ~/robots.txt` does load the file correctly in Vim.

Trying `:w` (without prior `:e`) makes Vim output `E13: file exists (add ! to override)`, even though it thinks it is operating on nonexistent file.

**Comment by DustinBrett** [comment]
I don't get a "Firefox's native menu" to dismiss and I am surprised you do. The fact my menu appears means it should not have shown Firefox's I would have thought as it's the context menu listener.

Also those steps for me in FF 101 works. As for FF 91, I am not sure tbh if I even support that, but I will look into if it's specific to older FF builds.

On cold open from Open With on robots.txt:
![image](https://user-images.githubusercontent.com/16656318/173138359-0a7c5376-3c12-40da-a26e-086e3f9c562e.png)

**Comment by DustinBrett** [comment]
This did indeed happen to me on FF 91 in BrowserStack. I will look into it further. If it works with latest FF than it might be something new I am using, but not sure tbh and vim.js is a bit tricky.

![image](https://user-images.githubusercontent.com/16656318/173139024-1f24243b-bf3f-47ef-b66f-a03de9179ed0.png)

**Comment by vi** [comment]
> I don't get a "Firefox's native menu" to dismiss and I am surprised you do.

That's because of a custom, non-default setting: `dom.event.contextmenu.enabled=false`.

**Comment by vi** [comment]
Also not reproducible on Chromium 102.

**Comment by DustinBrett** [comment]
It's possible the writing is a race condition on the read as I do one then the other to allow Vim to see the file. I will try and do it in a more sensible manner.
