### ISSUE TITLE
Closing Vim sometimes crashes app

### ISSUE THREAD

**Issue by vi** [DustinBrett/daedalOS#173]
In Tor Browser, opening the app, opening a folder, launching text editor on some file, then closing the text editor often makes browser to reload the page, losing session.

```
Navigated to https://dustinbrett.com/
Blocked https://dustinbrett.com/ from extracting canvas data because no user input was detected. _app-aea3b3505eafdf0f.js:1:388742
The resource at “https://dustinbrett.com/Users/Public/Icons/48x48/brain.webp” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. dustinbrett.com
The resource at “https://dustinbrett.com/Users/Public/Icons/48x48/doom.webp” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. dustinbrett.com
The resource at “https://dustinbrett.com/System/Icons/48x48/user.webp” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. dustinbrett.com
The resource at “https://dustinbrett.com/System/Icons/48x48/pc.webp” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. dustinbrett.com
The resource at “https://dustinbrett.com/System/Icons/48x48/shortcut.webp” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. dustinbrett.com
Navigated to https://dustinbrett.com/
Navigated to https://dustinbrett.com/
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    NextJS 31
framework-89f2f7d214569455.js:1:71382
Blocked https://dustinbrett.com/ from extracting canvas data because no user input was detected. _app-aea3b3505eafdf0f.js:1:388742
The resource at “https://dustinbrett.com/Users/Public/Icons/48x48/brain.webp” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. dustinbrett.com
The resource at “https://dustinbrett.com/Users/Public/Icons/48x48/doom.webp” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. dustinbrett.com
The resource at “https://dustinbrett.com/System/Icons/48x48/user.webp” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. dustinbrett.com
The resource at “https://dustinbrett.com/System/Icons/48x48/pc.webp” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. dustinbrett.com
The resource at “https://dustinbrett.com/System/Icons/48x48/shortcut.webp” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. dustinbrett.com
```

**Comment by DustinBrett** [comment]
Thanks for the report. I will try and re-create this to find a solution.

**Comment by vi** [comment]
Reproducible in another Firefox 91.10.0esr (customized) as well. Does not seem to be reproducible in Chromium.

**Comment by DustinBrett** [comment]
Ok thanks for the update. Had it been Monaco I had an idea, but if it really is any window then I have no idea. Will test it once I can.

**Comment by DustinBrett** [comment]
I am having this happen more now in FF in my testing, but only for Monaco. Could you tell me which other apps it happened in?

**Comment by vi** [comment]
Played more in Firefox and Tor browser and can't get the crash to reproduce without Monaco.

I got crash on closing Vim while also having two instances of Monaco open. Reproduced it two times (though second time was more contrived and involved prior closing Monaco without crash).

I remember crashes when closing file manager windows. Maybe they happened after Monaco closed before. Can't reproduce it now though.

Reproduced without Monaco, but with juggling other text editors around (e.g. Vim and Marked) for enough time.

Cannot find a stable Monaco-less repro sequence. Sometimes you need large number of various actions.

**Comment by DustinBrett** [comment]
I've found an actual issue in closing Monaco which I am fixing now.

https://github.com/DustinBrett/daedalOS/commit/02ec712a66e188ad4bd727739b5a41e3ff58221a

Vim I think may indeed also have some issue that's a little more random.

**Comment by vi** [comment]
Can windows be compartmentalized (e.g. run in separate Wasm instannces), so that crash in one window would only affect that window?

**Comment by DustinBrett** [comment]
The issue with running separate instances is to get off the main thread we lose a lot of interaction with the DOM. There are ways around it but it's not trivial. Some of the apps basically work like you are saying, where they are partially compartmentalized.

It's possible to do a lot more actually with web workers, wasm & canvas. Maybe one day I will try and make another version of daedalOS that I have full control over rendering. At that point I could do quite a bit more.
