### ISSUE TITLE
Maximized window height doesn't resize on viewport change

### ISSUE THREAD

**Issue by andrigamerita** [DustinBrett/daedalOS#174]
Hi!
Nice to see that this project has been growing a lot and getting better after many months ago, which was about the last time I explored it, until yesterday (for some reason).

The window manager in my opinion would need some practical improvements, as well as a fix for one (1) bug I currently found.

This is the **bug**:
- **Full-screen windows don't correctly resize vertically when the browser window is resized**
  - When a window in the daedalOS desktop is set to full-screen, it gets horizontally wider or shorter as the browser window gets horizontally wider or shorter. However, this doesn't happen when the browser windows is resized vertically, in which case the OS app window can either get shorter or taller than the entire desktop. See attached video: https://user-images.githubusercontent.com/37557992/179025637-89368263-2bb2-4d13-a5ff-c2753cc569a4.mp4 (download it if you have trouble playing it in the browser)

Apart from that bug, I think that the app experience would get better by also making these **improvements**:
- **Let windows get outside the screen border**
  - Exactly like on Microsoft Windows and basically any Linux desktop environment; While 1. the feature as it is now does make manually tiling windows easier, and 2. wanting for a window to be partially outside the screen might seem useless, I find it useful for quickly getting windows out of the way to focus on another, without minimizing and thus losing focus of them.
- **Add border and corner snapping/resizing**
  - Even here, exactly like on Windows >= 10, KDE, XFCE, Cinnamon, etc..; It's an useful feature on itself, but would solve the problem of manual tiling made harder if the improvement just above was to be made true

I hope that you find my suggestions useful! I would love to see them in the app :)

**Comment by DustinBrett** [comment]
Thanks for the bug report and suggestions!

- I will make a note of that resizing bug as I've seen it before but hadn't logged it specifically in that way. In general I'd like the windows to adjust better whenever the viewport changes.

- As for windows outside the desktop bounds, I will add this as a requested feature. I specifically didn't do it to avoid thinking about the problem of "lost windows", basically the user putting it outside the bounds and having it be basically gone. I will put some thought into solutions that match how Windows 10 does it.

- I do indeed have snapping on my roadmap and plan for it to emulate the way FancyZones works in PowerToys on Windows 10.

I will make updates to all my notes in regards to these comments and will prioritize them. Thanks again!

**Comment by DustinBrett** [comment]
I think I have some behaviors I can use for this feature:

- Windows must have at least 1px inside viewport at all times (Left/right/top resize handle)
- Windows titlebar cannot go above viewport
- Offscreen windows re-open adjusted on the offscreen axis (with 8px buffer inside viewport)

With this I think users should not lose a window and if they can't find it they can close and reopen the window. This is also how it seemed to work in Windows 10.

**Comment by DustinBrett** [comment]
And as for the snapping, perhaps I can indeed add this before I go full on with FancyZone's version. I have also noted the behaviors for this:

- Trigger corner snapping within 25x25 px corners
- Left/right snapping is 50% of screen when outside corner grids
- Trigger snapping when cursor is at edge of left/right/top viewport while dragging a window
- Top (non-corner) drag is for maximizing dragged window
- White box has 8px padding, 5px shadow & 300ms transitions on dimension changes (starting at 0x0)
- Cursor ripple effect when snapping starts

**Comment by markus-li** [comment]
> * Windows must have at least 1px inside viewport at all times (Left or right or top resize handle)

This may work well when in fullscreen, but in a browser window it can be very hard to grab the window. In my opinion a few more pixels would be better, like the 8px buffer offscreen windows are adjusted to?

**Comment by DustinBrett** [comment]
Hopefully fixed the window height issue. It was a little trickier to animate with framer motion because of having to account for the taskbar. But this commit should solve it. https://github.com/DustinBrett/daedalOS/commit/7f030448f5587691f61f107ecd71a5a749178e1a

As for the other 2 topics of this original issue, I'd like to continue those within Discussions:

- https://github.com/DustinBrett/daedalOS/discussions/120
- - https://github.com/DustinBrett/daedalOS/discussions/99

**Comment by DustinBrett** [comment]
Also added the same animation/logic to width. https://github.com/DustinBrett/daedalOS/commit/fbc3e3f61607ce9d6a9fba543be46a17893f1490
