### ISSUE TITLE
Exiting DOOM doesn't exit JS-DOS

### ISSUE THREAD

**Issue by ajmeese7** [DustinBrett/daedalOS#176]
When you click "Exit Game" in DOOM, it exits back to the JS-DOS command line, rather than simply exiting the DOS player and closing the window.

This behavior can be configured via the `onExit` handler in the JS-DOS configuration, so I am sure the `emulator` library has a compatible handler as well.

**Comment by DustinBrett** [comment]
Thanks for the report but I don't actually consider this a bug. It boots JS-DOS which auto runs Doom because it's in a jsdos bundle, but it's still in JS-DOS and I prefer the ability to be able to exit into DOS while running the Doom bundle so that I could do things to the files, if I so chose.
