### ISSUE TITLE
Linux image doesn't initialize to prompt

### ISSUE THREAD

**Issue by ajmeese7** [DustinBrett/daedalOS#191]
I'm not sure if this is an issue with the image or with your implementation of the emulator, so I just wanted to mention it here in case you were not already aware.

Whenever the *Linux* image finishes the boot process with the following (timestamp varies):

```
[   15.033504] random: crng init done
```

It appears to hang, with no indication that the boot process has finished and that the CLI is now interactive. Running a command like `whoami` indicates that the initialization has actually finished and then the prompt (`~% `) actually shows up, but before then the user is left guessing as to whether it is ready or not. Pressing the enter key also works, but the issue of not being sure whether it is ready before then still exists.

Update: Just realized that this is the same as #141, but you mentioned wanting to explore the possibility of a new image to resolve it. Leaving this open until I hear your thoughts :)

**Comment by DustinBrett** [comment]
Yes I had noticed that a while ago and it seemed to be part of the image I used which I got from v86. I will keep this open to make a note of finding a better image if possible. But if I cant find one I may just keep this as is cause the image has 9p setup and works otherwise.

**Comment by DustinBrett** [comment]
Added bzimage support and went with a newer linux .bin file that v86 has on their site. Also has network and 9p fs support.
