### ISSUE TITLE
Python `print` not showing in stdout

### ISSUE THREAD

**Issue by ajmeese7** [DustinBrett/daedalOS#193]
Running something such as `py print("test")` in the Terminal does not show any output, and I have noticed the same problem when running a simple Python script only containing `print("test")`.

This is the only command that I have noticed the problem with, as things like `py 1+1` and your example of `py import sys; sys.version` work as expected. I searched through the `pyodide` open and closed issues and did not notice anyone else reporting similar problems, which leads me to believe that this may be a problem on the end of `daedalOS` rather than in their implementation.

**Comment by DustinBrett** [comment]
I think this has more to do with where I am reading the output from for Pyodide. I think `print` and `stdout` have some kind of thing where it's one or the other. At one point I had a combined way to make it work but then an upgrade changed out Pyodide was doing it. I will look into a way for `print` and everything else to work in tandem.

**Comment by DustinBrett** [comment]
I've fixed this by having it check stdout if the normal results are empty.

**Comment by DustinBrett** [comment]
@ajmeese7 Thanks for reporting these issues btw. Much appreciated. Some of them I have a blind spot to after years of working on this thing. And others I hadn't found yet.

**Comment by ajmeese7** [comment]
My pleasure! Love the project, keep up the great work.
