### ISSUE TITLE
tilde key not working in js dos

### ISSUE THREAD

**Issue by glitch128** [DustinBrett/daedalOS#232]
the tilde key does not work in js dos. when I press it, nothing is typed.

**Comment by DustinBrett** [comment]
That does indeed seem to be the case. But it looks to be that way for jsdos in general as I see the same thing on https://dos.zone/

Perhaps you could post on their issue board as I'd rather the fix comes from them unless it's blocking to core usage of daedalOS.

https://github.com/caiiiycuk/js-dos
