### ISSUE TITLE
url leads to nothing

### ISSUE THREAD

**Issue by NAAAAAAAAA1212** [DustinBrett/daedalOS#242]
after the computer downloaded an URL, it cannot lead to any pages

**Comment by DustinBrett** [comment]
Ya I had considered making them point to the real domain. I will work on this.

**Comment by DustinBrett** [comment]
Went ahead and added it to latest build. Will post on live site asap.

https://github.com/DustinBrett/daedalOS/commit/95d62806f6f0943280dfcda4f1e7e19072a17d2a
