### ISSUE TITLE
Typing into a Virtual x86 app will also send keystrokes to other instances

### ISSUE THREAD

**Issue by alanboy** [DustinBrett/daedalOS#248]
Repro steps:
* Open Kolibri image
* Open linux.bin image

Focus the Kolibri window and type anything, you'll see keystrokes also being typed into the linux.bin window.

<img width="936" alt="image" src="https://user-images.githubusercontent.com/527987/209453325-6cf88155-31e1-4026-bd5e-a834521d4984.png">

**Comment by DustinBrett** [comment]
Thanks! I only recently allowed multiple instances of v86 when I saw an example on their site. I'll check if the issue happens there also and if not I'll see how I can remedy it.

**Comment by DustinBrett** [comment]
Fixed this. Turns out kb need to be turned on and off on each instance.

https://github.com/DustinBrett/daedalOS/commit/b68c1327eef86f32904cc4593219b67f59057c36
