### ISSUE TITLE
[ₛₘₐₗₗ fix] desktop icons not centered

### ISSUE THREAD

**Issue by glitch128** [DustinBrett/daedalOS#253]
this is a small fix, doesn't really affect anything, but the desktop icons aren't centered
![image](https://user-images.githubusercontent.com/78228404/211079480-e5fd9878-f6b6-4dfa-8b4a-c8a3b15c6ee3.png)

**Comment by DustinBrett** [comment]
Can you clarify what you mean by not centered? How would you expect it to look? Centered in reference to what? The entire icon or part of it or the grid? Thanks.

**Comment by glitch128** [comment]
ok, so my laptop has a camera directly in the center above the screen, but the center desktop icon doesn't align with the camera

**Comment by DustinBrett** [comment]
I see. Ya this is on purpose as the icon grid exactly matches it's position and size on Windows 10. This won't likely change, but thanks for pointing it out.
