### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by milkawa** [DustinBrett/daedalOS#264]
nodejs: v18.13.0(LTS)
yarn: 1.22.19
npm: 9.3.1
Compilation details:
hyfhao@localhost:~/daedalOS$ yarn build
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: fetch --tags
Directory: /home/hyfhao/.cache/yarn/v6/.tmp/f7f9077a7e79efd82dab209cc317b089
Output:
fatal: Unreachable 'https://github.com/jvilk/BrowserFS.git/'：Failed to connect to github.com port 443 after 31223 ms: Couldn't connect to server
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Operational detail:
hyfhao@localhost:~/daedalOS$ yarn start
yarn run v1.22.19
$ next build && next start
/bin/sh: 1: next: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by DustinBrett** [comment]
Seems like `next` isn't found. That package is in the dependencies and should be installed when `yarn` is ran.

**Comment by DustinBrett** [comment]
How do you get this result? Could you walk me through reproducing this?

**Comment by DustinBrett** [comment]
Looks like a git issue and not related to the repo. Try to clone it again and make sure you have git setup right to do `yarn`. If `node_modules/next` exists then it should work.
