### ISSUE TITLE
Viewport is too tall before initial focus in Chrome Incognito Mobile

### ISSUE THREAD

**Issue by DustinBrett** [DustinBrett/daedalOS#274]
Main element goes beyond height of viewport until tab/window is touched. This doesn't always happen, but touching always fixing it.

**Comment by DustinBrett** [comment]
I have yet to figure this out. If I open Chrome Incoginto, some of the time the height is wrong. If I click anywhere it triggers resize and changes the height. Seems like a Chrome bug but I can't confirm.

Tested this values on my S21 and it's 1021px before clicking, 718px after.
```js
const { height: computedDocumentHeight } =
    document.documentElement.getBoundingClientRect();
const { height: computedDesktopHeight } =
    desktopRef.current.getBoundingClientRect();

setDimensions({
    computedDesktopHeight,
    computedDocumentHeight,
    desktopClientHeight: desktopRef.current.clientHeight,
    documentClientHeight: document.documentElement.clientHeight,
    innerHeight: window.innerHeight,
    offsetHeight: desktopRef.current.offsetHeight,
    outerHeight: window.outerHeight,
    screenHeight: window.screen.height,
    scrollHeight: desktopRef.current.scrollHeight,
    visualViewportHeight: window.visualViewport?.height || 0,
});
```

**Comment by DustinBrett** [comment]
This issue happens with a fresh Next.js app and doesn't happen with Twitters homepage footer. So perhaps Next.js is part of the issue.

**Comment by DustinBrett** [comment]
Made an issue on Next.js as I can't think what else it is atm. https://github.com/vercel/next.js/issues/47839

**Comment by DustinBrett** [comment]
Finally think I figured out a fix. I didn't figure out why the height changes the way it does on mobile, but I fixed it anyway.

https://github.com/DustinBrett/daedalOS/commit/7667dd1d28c3948e16328b0f3374aadb3f90ca2b

**Comment by DustinBrett** [comment]
Yet more specificness. https://github.com/DustinBrett/daedalOS/commit/4bc4b1ea5a7a7d9d72bf31adb7873461cad62b69

I think this fix is jank but I will try and target it to Android Chrome for now until I figure out a better solution. This is a bug imo in the browser so it lies to me and makes it hard to detect a real case of it occuring.

**Comment by DustinBrett** [comment]
Ok yet another fix to get it working on prod builds. I think it worked before because of the double triggering `useEffect`'s on strict React dev.

https://github.com/DustinBrett/daedalOS/commit/7c195118f6e11029db85c74d8172e3d0b2fbd9db

**Comment by FIIFE** [comment]
Hi, i've stumbled across [this answer](https://stackoverflow.com/a/77879573/2521372) that I think you might be interested in.

**Comment by DustinBrett** [comment]
> Hi, i've stumbled across [this answer](https://stackoverflow.com/a/77879573/2521372) that I think you might be interested in.

Thanks for this info. Interestingly I got another comment about this bug today, after a year of it being closed.

https://github.com/vercel/next.js/discussions/63724

I will look into changing my solution possibly, but at the moment I was able to finally fix it most of the time.
