### ISSUE TITLE
Shutdown button erases everything without warning

### ISSUE THREAD

**Issue by kevadesu** [DustinBrett/daedalOS#278]
So basically I wanted to see what the power key did and it just cleared my session and had to upload things again. Is there any way to backup and restore things or atleast add a warning?

**Comment by DustinBrett** [comment]
Hey, thanks for the feedback. I will consider this for the future as possible a popup. Currently there is a tooltip that explains this will happen, but indeed it is a bit quick and can surprise people I suppose. As for saving the state, there is `/session.json` for some stuff but for files that have been written I currently have no way to backup this if it's reset.

![image](https://user-images.githubusercontent.com/16656318/223774101-bdad8eb6-14a6-443c-a246-54b22f671ad6.png)
