### ISSUE TITLE
Node 18 is required because of @huggingface/inference

### ISSUE THREAD

**Issue by SSP6904** [DustinBrett/daedalOS#283]
Hello!

I'm getting a issue where the testing workflow, which I forked from this repo, is giving me a weird error about the version for some reason..

Error Log:

`error @huggingface/inference@1.6.0: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.19.1"`

That's all I really got and it failed because of that.

Is that normal or is it the node version it requires?

Thanks alot!

**Comment by DustinBrett** [comment]
Yes this is a new and annoying issue I am thinking how best to resolve. I wanted the typings so I included this file but it meant I had to do `--ignore-engines` during some yarn commands. I will probably get rid of this dependency if I can't find a way around this. Even that package doesn't need Node 18, not for browser purposes which is my use case.

**Comment by SSP6904** [comment]
Alright! I got it to work now!

I'm still a little confused about that package and this project, but it's cool anyway!

What I basically did is run `yarn --ignore-engines` in the repo cloned and run `yarn build:fs` and `yarn dev` and it seamed to work in the browser at least.

Thanks a lot man! 👍

**Comment by DustinBrett** [comment]
I plan to fix this package quite soon so I will keep this issue open. Using `--ignore-engines` is just a stopgap. I use the package for the HuggingFace Inference API interface, which can run in the browser or on node. Sadly they've made their library require node 18 but that is not needed for the browser use case. I will probably make my own typings and just load hugging face library dynamically.

**Comment by DustinBrett** [comment]
Switched back to using the pre-built file instead of via npm with it's unnecessary Node 18 restriction.

https://github.com/DustinBrett/daedalOS/commit/bedf3ccf43ca66060d10df0134a38d49d9f5dc1e
