### ISSUE TITLE
Add debian standard iso to emulators

### ISSUE THREAD

**Issue by glitch128** [DustinBrett/daedalOS#285]
hey, quick thing, could you add the iso from [this link](https://cdimage.debian.org/debian-cd/current-live/i386/iso-hybrid/debian-live-11.6.0-i386-standard.iso) to the disk images folder? the size is 1.3 GB and it runs on https://copy.sh, but the filesize is too large to upload to the website. the file is from the debian website.

**Comment by DustinBrett** [comment]
I am able to drag/drop this onto the website to run locally.

![image](https://user-images.githubusercontent.com/16656318/227642572-9c163a96-578f-4110-b373-34ea02b0159d.png)

**Comment by glitch128** [comment]
oh, before, if i tried to upload something more than a GB, then it would fail. wait, my chromebook just crashed while uploading it

**Comment by glitch128** [comment]
accessed it by using map directory, and i think it froze my chromebook

**Comment by DustinBrett** [comment]
Ya I am not sure tbh but there is indeed a limit to how big the files can be. If you want to add larger files it's best to fork the repo and add it that way. Thanks for the suggestion to add debian iso but I'd rather not have such a large file hosted or in the repo.
