### ISSUE TITLE
"Proxy" Chromium Browser

### ISSUE THREAD

**Issue by hosykynam0619ch2008-ies** [DustinBrett/daedalOS#286]
### Discussed in https://github.com/DustinBrett/daedalOS/discussions/282

<div type='discussions-op-text'>

<sup>Originally posted by **hosykynam0619ch2008-ies** March 19, 2023</sup>
Hi Dustin, I love your project! As right now you're still using iFrame for the browser :(, I know there's might be a lot of request asking you to use proxy as the chromium, but I know it's hard hosting proxy, anddd coding the browser btw ._., so I'm here to ask you if you could replace the browser with this: https://r.studyschooltoday.eu.org/ , I've found this website which is a proxy server but it's design to look exactly like chrome, which fits the deadalOS browser, it's save you time of making a browser, instead of building a browser, just embed this site as an iframe and enjoy! I'm sorry if this site not work for you, sooooooo.... maybe give it a try, I (*personaly*) think this design fits..... the browser.

Thank you for reading this, I appreciate your work 😊</div>

**Comment by DustinBrett** [comment]
Thanks for posting this. I will respond now in the original discussion. https://github.com/DustinBrett/daedalOS/discussions/282
