### ISSUE TITLE
How to change the web browser title

### ISSUE THREAD

**Issue by rocheston** [DustinBrett/daedalOS#306]
The web browser title changes depending on what you click like File Manager etc. I want a consistent web browser title like 'University of Chicago Cyber Labs'

We need this for XDR firewall. How do you think I could do this?

**Comment by rocheston** [comment]
Fixed it. Thanks. Closing it now.

**Comment by DustinBrett** [comment]
Feel free to post your solution. I would have suggested removing the code in Metadata which dynamically changes the title.
