### ISSUE TITLE
Coding error

### ISSUE THREAD

**Issue by sbach89** [DustinBrett/daedalOS#32]
Module not found: Can't resolve 'components/system/Desktop/Wallpapers/vantaWaves'
> 1 | import vantaWaves from "components/system/Desktop/Wallpapers/vantaWaves";
  2 |
  3 | const wallpaper = vantaWaves({
  4 |   color: 0x192b34,

Simple fix, I just changed `wallpaper` from the git clone to `Wallpaper`. Case sensitive.

**Comment by DustinBrett** [comment]
Thanks I will be fixing this today. I had renamed this folder but Git didn't take the change the way I did it.

**Comment by DustinBrett** [comment]
Fixed in https://github.com/DustinBrett/daedalOS/commit/56c17e88d6fb12d127bc31d9eb9854b8f3165ea5, thanks for the report!
