### ISSUE TITLE
How can I change the start pi button into a round circle?

### ISSUE THREAD

**Issue by rocheston** [DustinBrett/daedalOS#321]
How can I modify the start pi button to be a round circle? Can I edit any files to add a png/jpg?

**Comment by rocheston** [comment]
StyledStartButton.ts. Thanks. Closing this now.

**Comment by DustinBrett** [comment]
https://github.com/DustinBrett/daedalOS/blob/main/components/system/Taskbar/StartButton/StartButtonIcon.tsx
