### ISSUE TITLE
PDF doesn't show

### ISSUE THREAD

**Issue by rikhuijzer** [DustinBrett/daedalOS#331]
Nice website man. It's really amazing what is possible. Small issue: when clicking on "PDF" in the start menu, the viewer just appear to hang with a blue rotating cursor. I've tried both Firefox and Edge.

![image](https://github.com/DustinBrett/daedalOS/assets/20724914/967c7a61-93d3-4f90-8d63-f2a45069a380)

**Comment by DustinBrett** [comment]
Thanks for mentioning this! I had indeed logged this but forgot to deal with it sooner as it's quite confusing. It looks to be loading but just never leaves that state because I forgot to unset it when a file isn't selected for the PDF viewer.

**Comment by DustinBrett** [comment]
Fixed https://github.com/DustinBrett/daedalOS/commit/c601ce2a291dbc73dc39ed596bdb5f574bd54e9e
