### ISSUE TITLE
Copying folder to its subfolder causes recursive bug

### ISSUE THREAD

**Issue by reverse123** [DustinBrett/daedalOS#346]
There was a bug when I think I copied one folder to its subfolder or something like this. It recursively copied folders until I stopped the process. There were thousands of folders created one inside the other.

**Comment by DustinBrett** [comment]
Thanks for the report, that does indeed sound like a bug. Would you be able to clarify the recreation steps as I haven't been able to make this happen. It sounds very likely possible though if done in some order.

**Comment by DustinBrett** [comment]
> There was a bug when I think I copied one folder to its subfolder or something like this. It recursively copied folders until I stopped the process. There were thousands of folders created one inside the other.

I think I have recreated it via the "Copy" context menu or via Ctrl+C. I will have a fix asap.

**Comment by DustinBrett** [comment]
Added a fix to remove the parent directories from paste lists.
