### ISSUE TITLE
website access through browser

### ISSUE THREAD

**Issue by ai777ai** [DustinBrett/daedalOS#349]
When trying to access a website through the browser i get a refused connection error!

**Comment by DustinBrett** [comment]
Yes that is expected, only sites that support CORS will work, such as the ones I have added as icons below the address bar. Also IPFS url's work as I have it go through a gateway. This is unavoidable with client-side code.

**Comment by glitch128** [comment]
hey, there is actually an extension that I use that allows that.
https://chromewebstore.google.com/detail/hiframe-the-hyper-iframe/joibipdfkleencgfgbbncoheaekffdfn

**Comment by glitch128** [comment]
no, sorry. As far as I know, with current web technologies, x86_64 emulation isn't possible.

**Comment by DustinBrettGlint** [comment]
Yes indeed with v86 we cannot run anything x64. It's possible with other emulators I think, but v86 was easiest to integrate.

**Comment by glitch128** [comment]
Also, if I remember correctly, the boxedwine application is the 32-bit variant, right?
