### ISSUE TITLE
Typing in console from mobile device is causing double characters

### ISSUE THREAD

**Issue by rbeesley** [DustinBrett/daedalOS#39]
This does not seem to be the same issue as #4 but might be related because of the feature area. I opened the console in Edge on my Duo. This was using SwiftKey as my keyboard. Typing "ls" at the prompt resulted in "LLSS".

The initial capital "L" makes some sense as SwiftKey is just using its default casing for a new line of text. There might be a way to hint to the keyboard to not provide an uppercase. I pressed enter thinking that maybe it was an echo problem, but it complained about not finding "LLSS." 

Starting again, I typed L. Then I had to press backspace twice to get it to delete the second one. I typed S, and the default casing was still capitalized. I pressed backspace twice again until the prompt read "LS". Then I pressed enter and it showed the directory listing.

Edit : These details aren't 100% correct. The capital "s" seemed to happen when I deleted the second of the preceding double "l", otherwise it produced "LLss".

**Comment by DustinBrett** [comment]
Thanks for the clear bug report. This should be enough for me to look into it, thanks!

**Comment by DustinBrett** [comment]
It doesn't happen on my S21 or S8 but I have indeed noticed it in BrowserStack. I will try and understand what is happening with the Keyboard events. Any suggestions welcome.

**Comment by rbeesley** [comment]
https://user-images.githubusercontent.com/3703112/152592146-7fa72ecb-b6c6-4b92-96dc-818ea121cb61.mp4

Almost completely worthless after I compressed it to fit on GH, but this is a video recreating the issue. No real idea what to suggest. I believe I initially found this on A10, and have upgraded my device to A11 where it still reproduces.

**Comment by rbeesley** [comment]
Okay, some more information.

The only two keyboards I tested which worked without issue were Hacker's Keyboard and Gboard, but only in handwriting mode.

Gboard in regular mode, SwiftKey, and Unexpected Keyboard showed the double characters. Swype wasn't showing double characters, but would seemingly auto-correct when pressing return.

So in a way not completely useful, the behavior is influenced by the keyboard and the behavior isn't consistent in a way I'd expect.

I'm going to guess that you are using Samsung's default keyboard for the devices you've tested which work?

**Comment by rbeesley** [comment]
Thinking about the pattern here, the keyboards which I know that fail, they are looking at the edit textbox buffers to provide corrections. The way we did this with Swype years ago, was that we'd actually send keys to the buffer to delete text and replace it. I'll bet that Hacker's Keyboard doesn't try to hook into the buffer at all. That would be a path to investigate. What the keyboards are reading from the buffer is probably incorrect in some way, maybe UTF-8 vs. ASCII characters? If there's some encoding problems the character streams might be getting confused.

**Comment by DustinBrett** [comment]
Thanks for this detailed report! I will spend some time looking at this during the week. I think I just need to do some better debugging as to what keyCode's I am getting because tbh I haven't dug deep enough yet.

**Comment by No-one-important** [comment]
I have found this is a common issue on other websites with a console type interface e.g. [repl.it](replit.com)

**Comment by DustinBrett** [comment]
Do you happen to have any issues/discussions where people have reported this for other apps? I am trying to think if it's a well known issue or if there is a simple fix.

**Comment by No-one-important** [comment]
no unfortunately not
I didn't report it when I found it as I wasn't sure if it was just my phone
(I had a very buggy phone at the time) and have not seen any reports of it

**Comment by DustinBrett** [comment]
Thanks for the update. I will keep looking into this.

**Comment by DustinBrett** [comment]
I can't make this happen in BrowerStack or locally. Gonna close it for now until I hear about more people running into it.
