### ISSUE TITLE
New special icons can spawn over current icons

### ISSUE THREAD

**Issue by Ser-Gen** [DustinBrett/daedalOS#423]
I opened your amazing site today and one of the icons was placed over another.
I see this position of the shortcut `My Travel Story.url` in this file
https://dustinbrett.com/_next/static/chunks/pages/_app-3f1f8ba682a4ee67.js

```
"/Users/Public/Desktop/My Travel Story.url": {
	"gridColumnStart": 2,
	"gridRowStart": 2
}
```

Maybe this issue is related: #399

![image](https://github.com/DustinBrett/daedalOS/assets/1856145/d9a3fc72-4300-4378-8d59-25dcbc85ec26)

**Comment by DustinBrett** [comment]
Thank you for reporting this. I actually had noticed this new issue recently and thought I fixed/deployed a change. But if it's happening to you then I am unsure tbh what is going on and I will look into it. Are you able to reload the page and clear cache, without reset the session, just the browser cache? The other icon should be below that travel story one and my new code was suppose to auto fix this.

https://github.com/DustinBrett/daedalOS/commit/777ab673f0843e9ca503d723170d8e99e896eb54

**Comment by DustinBrett** [comment]
And indeed #399 is similar but I had specifically set all new icons to have positions in hopes of not having this issue again. When I get off work I will look into how to recreate the issue you are having. Could you post the contents of your `/session.json` file also? Thanks!

**Comment by Ser-Gen** [comment]
By the way I noticed now that when I pulled the session file from the browser to the desktop, it had less data than when I use the context menu item Download

Looks like another question, do I need to make a separate task for this?

**Comment by DustinBrett** [comment]
If you moved the session file out it may have made a new one, so I am not sure if that is a bug but if you could clarify the issue and what you did to recreate it then I can look into the session issue separately if there is one.

**Comment by DustinBrett** [comment]
> I'm afraid I'm interfering with further investigation: when I saw the overlapping icons, I thought it was just a rendering error and moved the icon sideways. It was only later that I realized it was a positioning error.
> 
> Anyway, I've attached the session file. [session.json](https://github.com/DustinBrett/daedalOS/files/15083391/session.json)

I will take a look at the file thanks! That visual you showed me looks like both icons wanted grid position 2, 2. I thought I'd fixed that but assuming you don't have an older version of daedalOS then it might not be fixed.

**Comment by DustinBrett** [comment]
> I'm afraid I'm interfering with further investigation: when I saw the overlapping icons, I thought it was just a rendering error and moved the icon sideways. It was only later that I realized it was a positioning error.
> 
> Anyway, I've attached the session file. [session.json](https://github.com/DustinBrett/daedalOS/files/15083391/session.json)

I see from the session file you had a file called "Memento MoriMemento MoriMemento Mori.url" and I see in the screenshot that one of the overlapping icons has text which is long enough to be truncated (...). I will look further into how this circumstance could have caused the issue.

**Comment by DustinBrett** [comment]
I think I see the problem. My new icon fixing code is only to fix default icons being in the way of other default icons. Perhaps you renamed `Memento Mori.url` to `Memento MoriMemento MoriMemento Mori.url` and left it in it's original position before I moved it down in the defaults and added `My Travel Story.url` in its place. So my icon fixing code doesn't look for the new icon and doesn't move it. I've attempted to fix it and will deploy the code later today.

https://github.com/DustinBrett/daedalOS/commit/f0feee7af7c69f596c64243843a3bf9c034aa0bb

**Comment by Ser-Gen** [comment]
Right! Now I remember I've been experimenting with icon names for a while.

I have now reopened daedalOS and everything displays fine now.
Unfortunately I don't know how else to test if the updated code works.

**Comment by DustinBrett** [comment]
> Right! Now I remember I've been experimenting with icon names for a while.
> 
> I have now reopened daedalOS and everything displays fine now. Unfortunately I don't know how else to test if the updated code works.

Thanks for following up! I think once you moved the icon it will be hard to show it broken again without modifying your session.json file. I actually haven't deployed the fix yet onto my website, but I am hopeful that it will solve the issue for anyone who has previously visited my site and renamed or moved icons into the positions of the default icons.

I will deploy tonight hopefully and then will do some testing before closing this issue.

**Comment by DustinBrett** [comment]
I've deployed the fix so we will see how it goes. I tried to test the scenarios I could think of, eventually I will make some e2e tests for it, but for now I will close this until I hear another report.
