### ISSUE TITLE
Feature Request: Micropip

### ISSUE THREAD

**Issue by davey422** [DustinBrett/daedalOS#437]
Would it be possible to add Micropip?

**Comment by DustinBrett** [comment]
I had never heard of this package manager but it does indeed seem possible. I will work more on this commit later tonight. It's cool that it has a built in package manager. It looks like it gets the files directly from https://files.pythonhosted.org/packages/ with CORS enabled.

![image](https://github.com/DustinBrett/daedalOS/assets/16656318/2605d8b4-81a3-49a1-806c-fe495b46ad42)

![image](https://github.com/DustinBrett/daedalOS/assets/16656318/27ad3855-a320-4195-a640-e6c174b3385b)

![image](https://github.com/DustinBrett/daedalOS/assets/16656318/f388f482-f423-4378-b201-9c5144a4b03b)
