### ISSUE TITLE
Applying sorting method from context menu activates selection area

### ISSUE THREAD

**Issue by antonfilka** [DustinBrett/daedalOS#489]
https://github.com/user-attachments/assets/006e3792-c452-4c34-bf13-bef3f47d6525

**Comment by DustinBrett** [comment]
Are you able to recreate this consistently? Could you give me more information about your browser/computer?

I was not able to make this occur but doing what you did in the video.

**Comment by antonfilka** [comment]
Sure
Hardware: MacBook Pro M1 chip
Software: macOS Sequoia 15.0, Google Chrome Version 131.0.6778.70 (Official Build) (arm64)

Steps to reproduce:
- Open https://dustinbrett.com/ in incognito tab to get rid of extensions effects
- Refresh the page
- Right click on empty area to trigger context menu 
- Select "Sort by" option
- Select any available sorting method in submenu
- After context menu close and sorting applied, moving mouse causes selection area while not pressing any mouse button

Issue exists while using both touchpad and mouse

**Comment by DustinBrett** [comment]
Thanks for that info. It was indeed an issue with Safari passing the mouseup event to the menu instead of the file manager. I have changed it so mouseup is monitored on the entire window.

https://github.com/DustinBrett/daedalOS/commit/6995907262a05b82916d5b29700da809f0c4b578

**Comment by DustinBrett** [comment]
I changed to making the container for the menu non-interactive, so when it opens it doesnt get the mouseup event. Using mouseup on window seemed to cause lag.
