### ISSUE TITLE
Autocomplete bug on 2nd tab with quoted suggestions

### ISSUE THREAD

**Issue by DustinBrett** [DustinBrett/daedalOS#64]
1. Go to Terminal
2. Make folder `A Test`
3. `cd A<TAB>`
4. Press `<TAB>` again
5. Result: `cd "A"A Test"`
6. Expected no change

**Comment by hello-smile6** [comment]
Maybe:
```
if(autoCompleteItem.startsWith(currentCommandLine)) {
  currentCommandLine=autoCompleteItem;
}
```
Or something like that?

**Comment by DustinBrett** [comment]
I think it's likely an issue in `local-echo` that needs adjusting. I have had to make quite a few changes to the library.

**Comment by DustinBrett** [comment]
Fixed this by comparing to the last completed token. The basic issue was it trying to auto complete twice anyway.
