### ISSUE TITLE
Git cloning into a mapped directory fails

### ISSUE THREAD

**Issue by DustinBrett** [DustinBrett/daedalOS#75]
Seems like write and possibly large reads from mapped drives are having issues. If I open a mapped drive in terminal and run git, the folder is made but files are not written.

**Comment by hello-smile6** [comment]
Strange

**Comment by hello-smile6** [comment]
May be an issue with API support in BrowserFS, I encountered the same issue while attempting to clone a repository using isogit.

**Comment by DustinBrett** [comment]
Been digging more into this and starting to think it has something to do with symlinks. It does seem to be partly related to the way isogit wants to use `fs` which may not be supported with the File System Access API currently.

**Comment by hello-smile6** [comment]
> Been digging more into this and starting to think it has something to do with symlinks. It does seem to be partly related to the way isogit wants to use `fs` which may not be supported with the File System Access API currently.

Can you implement symlinks by creating a .symlinks file and reading from it, then creating a Nodejs script to create actual symlinks or update the file?

**Comment by DustinBrett** [comment]
I don't think it's possible to make real symlinks via the File System Access API but that is how IsoGit works on most GitHub repos it seems.

**Comment by hello-smile6** [comment]
> I don't think it's possible to make real symlinks via the File System Access API but that is how IsoGit works on most GitHub repos it seems.

Why not fake it, by creating a file with the locations of would-be symlinks and creating placeholder files where symlinks would be?

**Comment by DustinBrett** [comment]
Feel free to give it a go. I think it will be easier said than done that approach. And I also prefer not to fake those kinds of things.

**Comment by hello-smile6** [comment]
> Feel free to give it a go. I think it will be easier said than done that approach. And I also prefer not to fake those kinds of things.

I have no idea how to.

**Comment by hello-smile6** [comment]
Maybe [discourse.wicg.io](https://discourse.wicg.io/) is necessary. Unfortunately, some environments will never support symlinks, so faking it may be the only option.

**Comment by DustinBrett** [comment]
I tested this recently and it worked, although it did oddly make my computer slow which was a worry, but it was able to write so progress has been made and I am going to close this for now.
